### ISSUE TITLE
Installation conflicts with python > 3.6

### ISSUE THREAD

**Issue by aimirza** [knightlab-analyses/reference-frames#13]
Running `conda install tensorflow=1.10 tqdm nomkl` didnt install because of many conflicts. I realized it was because my conda installed using my current python version 3.7.6. Worked when I specified `python=3.6` when installing. You may want to include `python=3.6` in the first code `conda create -n songbird_env python=3.6 numpy=1.15.4 scikit-bio=0.5.5 seaborn pandas=0.23.4 -c conda-forge` to prevent this inconvenience for your future users.

**Comment by mortonjt** [comment]
@aimirza , thank you for identifying the dependency conflict! I've updated the readme.
