### ISSUE TITLE
Example ipython files don't work

### ISSUE THREAD

**Issue by antgonza** [knightlab-analyses/reference-frames#4]
If you try to open Figure1/simulation-benchmark ipynb via github, you get:
<img width="921" alt="Screen Shot 2019-04-24 at 6 26 07 AM" src="https://user-images.githubusercontent.com/2014559/56659258-e153d180-6659-11e9-99e2-0e8e9ffc1f70.png">

then, if you download the files and try to open them you get:
<img width="895" alt="Screen Shot 2019-04-24 at 6 22 40 AM" src="https://user-images.githubusercontent.com/2014559/56659259-e153d180-6659-11e9-9e15-fd0d122083be.png">

**Comment by mortonjt** [comment]
That is not good. Let me double check

**Comment by mortonjt** [comment]
Looks like the notebook somehow got corrupted before push.  PR at #5 is now up to address this.

**Comment by mortonjt** [comment]
@antgonza reopen if you are still having problems with this.
